[feat]update

diff --git a/shell/generate_cpp_compile_commands_cmake b/shell/generate_cpp_compile_commands_cmake
--- a/shell/generate_cpp_compile_commands_cmake
+++ b/shell/generate_cpp_compile_commands_cmake
@@ -1,13 +1,20 @@
 #!/bin/bash
 
-cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1
+cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 
 
-if [ ! -f "compile_commands.json"]; then
+if [ ! -f "compile_commands.json" ]; then
     echo "generate compile_commands.json first!!!"
     exit 1
 fi
 
 jq 'map(.command |= gsub("-mcmodel=medium";""))' compile_commands.json > compile_commands.tmp && mv compile_commands.tmp compile_commands.json
+if [ $? -ne 0 ]; then
+    echo "motify compile_commands.json fail!!!"
+    exit 1
+fi
+# jq 'map(.command |= gsub("-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk";""))' compile_commands.json > compile_commands.tmp && mv compile_commands.tmp compile_commands.json
+# jq 'map(.command |= gsub("/Library/Developer/CommandLineTools/usr/bin/c++";"/opt/homebrew/bin/c++-14"))' compile_commands.json > compile_commands.tmp && mv compile_commands.tmp compile_commands.json
+jq 'map(.command |= gsub("-fopenmp";""))' compile_commands.json > compile_commands.tmp && mv compile_commands.tmp compile_commands.json
 
 rm -rf CMakefiles Makefile cmake_install.cmake CMakeCache.txt
 
diff --git a/shell/generate_cpp_compile_commands_make b/shell/generate_cpp_compile_commands_make
--- a/shell/generate_cpp_compile_commands_make
+++ b/shell/generate_cpp_compile_commands_make
@@ -1,12 +1,27 @@
 #!/bin/bash
 
-bear -- make
-
-if [ ! -f "compile_commands.json"]; then
-    echo "generate compile_commands.json first!!!"
+if [ -f "Makefile" ]; then
+    file="Makefile"
+elif [ -f "makefile" ]; then
+    file="makefile"
+else
+    echo "not makefile exist!!!"
     exit 1
 fi
 
-jq 'map(.command |= gsub("-mcmodel=medium";""))' compile_commands.json > compile_commands.tmp && mv compile_commands.tmp compile_commands.json
+sed 's/-mcmodel=medium//g' "$file" > "tmp_makefile"
+bear -- make -f tmp_makefile
+
+if [ $? -ne 0 ]; then 
+    echo "generate fail!!!"
+    exit 1
+fi
+
+# if [ ! -f "compile_commands.json"]; then
+#     echo "generate compile_commands.json first!!!"
+#     exit 1
+# fi
+#
+# jq 'map(.command |= gsub("-mcmodel=medium";""))' compile_commands.json > compile_commands.tmp && mv compile_commands.tmp compile_commands.json
 
 echo "success!!!"
